"""§2 media offence-language pre-filter — HIGH RECALL, tuned for media sources (tier 2/3).

Court sources (tier 1: Indian Kanoon, hc_judgments) keep the STATUTE pre-filter — a judgment
always cites its sections, and that filter gates per-document billing. MEDIA is different:
newspapers report the OFFENCE, not the statute ("man held for raping a minor" cites nothing),
and they do so in many languages. A section-anchored, English-only filter therefore scores
every regional crime feed at zero by construction — the defect this fixes (issue: Phase 8 §2).

This filter is offence-LANGUAGE and HIGH RECALL / low precision. Its ONLY job is to skip a
document that is OBVIOUSLY irrelevant, so we do not pay an LLM to read it. Gemini's ``in_scope``
boolean makes the actual scope decision. Missing a true case is the operator's red line, so we
optimise for recall and accept false positives — a false positive costs one cheap LLM call,
which the scope gate then rejects.

Matching:
- ROMAN/English terms are WORD-BOUNDARIED (so "rape" does not fire inside "grape"/"draped" and
  "minor" not inside ordinary "minor injury" — those boundaries matter because English feeds
  run through the same filter).
- NATIVE-SCRIPT terms are matched as SUBSTRINGS (the scripts are distinctive; a Devanagari/
  Telugu/Tamil offence word in a document is signal). A few native substrings deliberately
  over-match (e.g. Devanagari रेप is inside रेपो / "repo rate") — kept, per the recall rule.

The term sets were built + adversarially reviewed by native-language sub-editors (one agent per
enabled language). A language whose set does not exist yet MUST keep its feed disabled — never
enabled to produce silent zeros (Phase 8 §4).
"""

from __future__ import annotations

import re

from pipeline.sources.hc_judgments import qualifies as statute_qualifies

__all__ = [
    "LANGUAGES_WITH_TERMS",
    "NATIVE_OFFENCE_TERMS",
    "ROMAN_OFFENCE_TERMS",
    "media_offence_hit",
    "offence_term_languages",
]

# Languages whose native-script offence-term set exists (the §4d enablement gate: a media feed
# in a language NOT listed here must stay enabled:false).
LANGUAGES_WITH_TERMS: tuple[str, ...] = (
    "hindi",
    "marathi",
    "tamil",
    "telugu",
)

# Roman / English offence terms — WORD-BOUNDARIED at match time (see module docstring).
ROMAN_OFFENCE_TERMS: frozenset[str] = frozenset(
    {
        "aabroo",
        "aabru",
        "aggravated sexual assault",
        "aghaityam",
        "asmat",
        "assault on a child",
        "atyachaar",
        "atyachar",
        "atyacharam",
        "atyacharaniki palpadda",
        "bal yaun shoshan",
        "balatkaar",
        "balatkar",
        "balatkaram",
        "balatkari",
        "chedchad",
        "chedkhani",
        "cherichi",
        "chhed chhad",
        "chhedchhad",
        "chhedkhani",
        "child abuse",
        "child sexual",
        "chimurdi",
        "darindagi",
        "deh shoshan",
        "disrobe",
        "disrobed",
        "durachar",
        "durachari",
        "duragatam",
        "dushkaram",
        "dushkarm",
        "dushkarmi",
        "eve teasing",
        "eve-teasing",
        "gang rape",
        "gang raped",
        "gang-rape",
        "gang-raped",
        "gangrape",
        "gangraped",
        "haivaniyat",
        "haiwaniyat",
        "ismat",
        "izzat luti",
        "jabardasti",
        "kamandhudu",
        "kamapishachi",
        "kamukudu",
        "karpalippu",
        "karpazhippu",
        "katpazhippu",
        "koottu karpazhippu",
        "kukarm",
        "kukarma",
        "kumbal karpazhippu",
        "laingik atyachar",
        "laingik chhal",
        "laingik shoshan",
        "laingika dadi",
        "laingika durviniyogam",
        "laingika vedhimpulu",
        "manabangam",
        "manabhangam",
        "minor balika",
        "minor boy",
        "minor girl",
        "molest",
        "molestation",
        "molested",
        "molester",
        "molesting",
        "naradham",
        "outrage of modesty",
        "outraged her modesty",
        "outraging modesty",
        "paaliyal",
        "paaliyal thollai",
        "paaliyal thunburuthal",
        "palatkaram",
        "paliyal vankodumai",
        "penetrative assault",
        "pocso",
        "poksho",
        "posco",
        "rape",
        "raped",
        "rapes",
        "raping",
        "rapist",
        "samuhik balatkar",
        "samuhik dushkarm",
        "samuhika atyacharam",
        "sextortion",
        "sexual",
        "sexual abuse",
        "sexual assault",
        "sexual harassment",
        "sexual offence",
        "sexual offense",
        "sexual violence",
        "sexually abused",
        "sexually assault",
        "sexually assaulted",
        "sexually harassed",
        "shadi ka jhansa",
        "sheelbhang",
        "shielbhang",
        "sodomised",
        "sodomy",
        "stalking",
        "thagatha uravu",
        "unnatural offence",
        "unnatural sex",
        "valluravu",
        "van kalavi",
        "van punarvu",
        "vankalavi",
        "vankodumai",
        "vanpunarvu",
        "vedhimpulu",
        "vedhinchi",
        "vinay bhang",
        "vinaybhang",
        "vinaybhanga",
        "voyeurism",
        "yaun durachar",
        "yaun hinsa",
        "yaun shoshan",
        "yaun utpidan",
        "yaun utpiran",
    }
)

# Native-script offence terms per language — matched as SUBSTRINGS.
NATIVE_OFFENCE_TERMS: dict[str, frozenset[str]] = {
    "hindi": frozenset(
        {
            "अगवा कर दुष्कर्म",
            "अनाचार",
            "अपहरण कर दुष्कर्म",
            "अप्राकृतिक कृत्य",
            "अप्राकृतिक यौन",
            "अश्लील इशारे",
            "अश्लील छेड़छाड़",
            "अश्लील वीडियो",
            "अश्लील हरकत",
            "अश्लील हरकत की",
            "अस्मत लूटने",
            "अस्मत लूटी",
            "अस्मत से खिलवाड़",
            "आबरू लूटने",
            "आबरू लूटी",
            "आबरू से खिलवाड़",
            "इज्जत तार-तार",
            "इज्जत लूटने",
            "इज्जत लूटी",
            "इज्जत से खिलवाड़",
            "किशोरी से दुष्कर्म",
            "कुकर्म",
            "कुकर्म किया",
            "गंदी हरकत",
            "गैंग रेप",
            "गैंगरेप",
            "गैंगरेप के आरोपी",
            "गैंगरेप पीड़िता",
            "छात्रा से छेड़छाड़",
            "छेड़खानी",
            "छेड़छाड़",
            "छेड़छाड़ का आरोप",
            "छेड़छाड़ का आरोपी",
            "छेड़छाड़ की",
            "छेड़छाड़ की कोशिश",
            "दरिंदगी",
            "दरिंदगी की",
            "दरिंदा",
            "दुराचार",
            "दुराचारी",
            "दुष्कर्म",
            "दुष्कर्म कर फरार",
            "दुष्कर्म कर हत्या",
            "दुष्कर्म का आरोप",
            "दुष्कर्म का आरोपी",
            "दुष्कर्म का प्रयास",
            "दुष्कर्म किया",
            "दुष्कर्म की कोशिश",
            "दुष्कर्म के बाद हत्या",
            "दुष्कर्म पीड़िता",
            "दुष्कर्मी",
            "देह शोषण",
            "नाबालिग से गैंगरेप",
            "नाबालिग से छेड़छाड़",
            "नाबालिग से दुष्कर्म",
            "नाबालिग से बलात्कार",
            "नाबालिग से रेप",
            "पॉक्सो",
            "पॉक्सो एक्ट",
            "पॉक्सो के तहत",
            "पोक्सो",
            "प्यार का झांसा",
            "बच्ची से दुष्कर्म",
            "बच्ची से बलात्कार",
            "बच्ची से रेप",
            "बलात संभोग",
            "बलात्कार",
            "बलात्कार कर",
            "बलात्कार का आरोप",
            "बलात्कार का प्रयास",
            "बलात्कार किया",
            "बलात्कार की कोशिश",
            "बलात्कार के आरोपी",
            "बलात्कार पीड़िता",
            "बलात्कारी",
            "बलात्संग",
            "बहला-फुसलाकर दुष्कर्म",
            "बाल यौन शोषण",
            "बाल शोषण",
            "बालिका से दुष्कर्म",
            "ब्लैकमेल कर दुष्कर्म",
            "मर्यादा भंग",
            "मासूम से दरिंदगी",
            "मासूम से दुष्कर्म",
            "यौन अपराध",
            "यौन उत्पीड़न",
            "यौन उत्पीड़न का आरोप",
            "यौन छेड़छाड़",
            "यौन दुराचार",
            "यौन दुर्व्यवहार",
            "यौन दुष्कर्म",
            "यौन प्रताड़ना",
            "यौन शोषण",
            "यौन शोषण की शिकार",
            "यौन हमला",
            "यौन हिंसा",
            "यौनाचार",
            "रेप",
            "रेप कर हत्या",
            "रेप का आरोप",
            "रेप किया",
            "रेप की कोशिश",
            "रेप के आरोप",
            "रेप केस",
            "रेप पीड़िता",
            "लज्जा भंग",
            "लाज लूटी",
            "वहशत",
            "वहशी",
            "शादी का झांसा",
            "शादी का झांसा देकर दुष्कर्म",
            "शादी का झांसा देकर बलात्कार",
            "शील भंग",
            "शीलभंग",
            "सामूहिक दुराचार",
            "सामूहिक दुष्कर्म",
            "सामूहिक दुष्कर्म का आरोप",
            "सामूहिक बलात्कार",
            "सामूहिक बलात्कार का आरोप",
            "सामूहिक रेप",
            "हैवान",
            "हैवानियत",
        }
    ),
    "marathi": frozenset(
        {
            "अत्याचार",
            "अत्याचारप्रकरणी",
            "अत्याचाराच्या",
            "अश्लील चाळे",
            "अश्लील वर्तन",
            "गँग रेप",
            "गँगरेप",
            "चिमुरडीवर अत्याचार",
            "छेडखानी",
            "छेडछाड",
            "छेडछाडप्रकरणी",
            "छेडछाडी",
            "जबरदस्ती",
            "जबरदस्ती संबंध",
            "तरुणीवर अत्याचार",
            "तरुणीवर बलात्कार",
            "दुष्कर्म",
            "दुष्कर्माच्या",
            "नराधम",
            "पोक्सो",
            "पोक्सो अंतर्गत",
            "पोक्सो कायदा",
            "पोक्सो कायद्यानुसार",
            "बलात्कार",
            "बलात्कार करून",
            "बलात्कार केला",
            "बलात्कार झाला",
            "बलात्कारप्रकरण",
            "बलात्कारप्रकरणी",
            "बलात्काराचं",
            "बलात्काराचा",
            "बलात्काराचा प्रयत्न",
            "बलात्काराचे",
            "बलात्काराच्या",
            "बलात्कारी",
            "बाल लैंगिक शोषण",
            "बालकावर अत्याचार",
            "बाललैंगिक अत्याचार",
            "बालिकेवर अत्याचार",
            "मुलीवर अत्याचार",
            "मुलीवर बलात्कार",
            "रेप",
            "लैंगिक अत्याचार",
            "लैंगिक अत्याचारप्रकरणी",
            "लैंगिक अत्याचाराच्या",
            "लैंगिक गैरवर्तन",
            "लैंगिक छळ",
            "लैंगिक छळवणूक",
            "लैंगिक शोषण",
            "लैंगिक हल्ला",
            "विनयभंग",
            "विनयभंगप्रकरणी",
            "विनयभंगाचा",
            "विनयभंगाच्या",
            "सामुहिक बलात्कार",
            "सामूहिक अत्याचार",
            "सामूहिक बलात्कार",
        }
    ),
    "tamil": frozenset(
        {
            "இழிவுபடுத்திய",
            "கண்ணியம் சிதைத்த",
            "கற்பழிக்க முயன்ற",
            "கற்பழிக்க முயற்சி",
            "கற்பழிக்கப்பட்ட",
            "கற்பழிக்கப்பட்டது",
            "கற்பழிக்கப்பட்டார்",
            "கற்பழிக்கப்பட்டாள்",
            "கற்பழித்த",
            "கற்பழித்தான்",
            "கற்பழித்தார்",
            "கற்பழித்து கொலை",
            "கற்பழித்து கொலை செய்த",
            "கற்பழிப்பில்",
            "கற்பழிப்பு",
            "கற்பழிப்பு சம்பவம்",
            "கற்பழிப்பு புகார்",
            "கற்பழிப்பு வழக்கு",
            "கற்பழிப்புக்கு",
            "கற்பழிப்புக்கு உள்ளான",
            "கும்பலாக கற்பழித்த",
            "கும்பல் கற்பழிப்பு",
            "கும்பல் வல்லுறவு",
            "குழந்தை மீது பாலியல்",
            "குழந்தைகள் பாலியல் குற்றங்கள் தடுப்புச் சட்டம்",
            "கூட்டாக கற்பழித்த",
            "கூட்டு கற்பழிப்பு",
            "கூட்டு பாலியல் வன்கொடுமை",
            "கூட்டு வல்லுறவு",
            "கௌரவம் குலைத்த",
            "சிறுமிக்கு பாலியல் தொல்லை",
            "சிறுமியை கடத்தி கற்பழித்த",
            "சிறுமியை கற்பழித்த",
            "சிறுமியை பலாத்காரம் செய்த",
            "சிறுமியை பாலியல் பலாத்காரம்",
            "தகாத உறவு",
            "தகாத முறையில் தொட்ட",
            "தகாத முறையில் நடந்துகொண்ட",
            "பலர் சேர்ந்து கற்பழித்த",
            "பலாத்காரம்",
            "பலாத்காரம் செய்த",
            "பள்ளி மாணவியிடம் தகாத",
            "பாக்சோ",
            "பாலியல் இச்சை",
            "பாலியல் இச்சையுடன் தொட்ட",
            "பாலியல் குற்றம்",
            "பாலியல் குற்றவாளி",
            "பாலியல் கொடுமை",
            "பாலியல் சித்திரவதை",
            "பாலியல் தாக்குதல்",
            "பாலியல் துன்புறுத்தல்",
            "பாலியல் துன்புறுத்திய",
            "பாலியல் தொல்லை",
            "பாலியல் தொல்லை கொடுத்த",
            "பாலியல் பலாத்காரத்துக்கு உள்ளான",
            "பாலியல் பலாத்காரம்",
            "பாலியல் பலாத்காரம் செய்த",
            "பாலியல் ரீதியாக",
            "பாலியல் ரீதியில் நடந்துகொண்ட",
            "பாலியல் வன்கொடுமை",
            "பாலியல் வன்முறை",
            "பாலியல் வல்லுறவு",
            "போக்சோ",
            "போக்சோ சட்டத்தின் கீழ்",
            "போக்சோ சட்டம்",
            "போக்சோ வழக்கு",
            "போக்ஸோ",
            "மரியாதையை சீர்குலைத்த",
            "மாணவியை கற்பழித்த",
            "மானபங்கப்படுத்த முயற்சி",
            "மானபங்கப்படுத்திய",
            "மானபங்கம்",
            "வன்கலவி",
            "வன்கலவிக்கு",
            "வன்புணர்ச்சி",
            "வன்புணர்வு",
            "வல்லுறவு",
        }
    ),
    "telugu": frozenset(
        {
            "laingika durvinियోగం",
            "అఘాయిత్యం",
            "అఘాయిత్యానికి పాల్పడ్డ",
            "అత్యాచార యత్నం",
            "అత్యాచారం",
            "అత్యాచారం చేశాడు",
            "అత్యాచారం చేశారు",
            "అత్యాచారం చేసి",
            "అత్యాచారయత్నం",
            "అత్యాచారానికి",
            "అత్యాచారానికి గురి",
            "అత్యాచారానికి పాల్పడ్డ",
            "అసభ్యంగా ప్రవర్తించి",
            "అసభ్యంగా ప్రవర్తించిన",
            "అసభ్యకర ప్రవర్తన",
            "ఈవ్ టీజింగ్",
            "కామంతో",
            "కామపిశాచి",
            "కామాంధుడి",
            "కామాంధుడు",
            "కాముకుడి",
            "కాముకుడు",
            "గ్యాంగ్ రేప్",
            "గ్యాంగ్‌రేప్",
            "చెరపట్టి",
            "చెరలో",
            "చెరిచాడు",
            "చెరిచి",
            "చెరిచిన",
            "దురాగతం",
            "దురాగతానికి పాల్పడ్డ",
            "పోక్సో",
            "పోక్సో కింద",
            "పోక్సో కేసు",
            "పోక్సో చట్టం",
            "పోక్సో యాక్ట్",
            "బట్టలు విప్పి",
            "మర్యాద భంగం",
            "మహిళ మర్యాదకు భంగం",
            "మానం దోచి",
            "మానం దోచుకున్న",
            "మానభంగం",
            "మానభంగయత్నం",
            "మానభంగానికి",
            "మానభంగానికి పాల్పడ్డ",
            "రేప్",
            "రేప్ చేసి",
            "రేప్‌కు పాల్పడ్డ",
            "లైంగిక దాడి",
            "లైంగిక దాడికి పాల్పడ్డ",
            "లైంగిక దుర్వినియోగం",
            "లైంగిక దోపిడీ",
            "లైంగిక వాంఛ తీర్చుకున్న",
            "లైంగిక వేధింపులకు గురి",
            "లైంగిక వేధింపులు",
            "లైంగికంగా వేధించి",
            "లైంగికంగా వేధించిన",
            "లైంగికదాడి",
            "లైంగికవేధింపులు",
            "లొంగదీసుకుని",
            "వివస్త్రను చేసి",
            "వేధించి",
            "వేధింపులు",
            "వేధిస్తూ",
            "సామూహిక అత్యాచారం",
            "సామూహిక అత్యాచారానికి",
        }
    ),
}

_ALL_NATIVE: frozenset[str] = frozenset().union(*NATIVE_OFFENCE_TERMS.values())

# One case-insensitive, word-boundaried alternation over the roman terms (longest first, so a
# multi-word term wins over its prefix). ASCII boundaries only, so it never splits native script.
_ROMAN_RE = re.compile(
    r"(?<![a-z])(?:"
    + "|".join(re.escape(t) for t in sorted(ROMAN_OFFENCE_TERMS, key=len, reverse=True))
    + r")(?![a-z])",
    re.IGNORECASE,
)


def media_offence_hit(text: str) -> bool:
    """True if ``text`` plausibly reports a sexual offence (any covered language). HIGH RECALL —
    a hit means "send to the LLM", not "this is in scope". Empty/non-str is never a hit."""
    if not isinstance(text, str) or not text:
        return False
    if _ROMAN_RE.search(text):
        return True
    if any(term in text for term in _ALL_NATIVE):
        return True
    # Retain the statute patterns as additional hits (a media report may cite a section).
    return statute_qualifies(text)


def offence_term_languages(text: str) -> list[str]:
    """Which covered languages' native offence terms appear in ``text`` (for accounting)."""
    if not isinstance(text, str) or not text:
        return []
    return [lang for lang, terms in NATIVE_OFFENCE_TERMS.items() if any(t in text for t in terms)]
